### ISSUE TITLE
type list of computer types and product types somewhere easier to reference

### ISSUE THREAD

**Issue by ycheng** [fourdollars/energy-tools#2]
For people who only need to read output, it's not obvious to find the list of computer types and product types. Put somewhere in a text file, or even README.md will be much easier for those users to find it.

Which product type would you like to verify?
[1] Desktop, Integrated Desktop, and Notebook Computers
[2] Workstations
[3] Small-scale Servers
[4] Thin Clients
--------------------------------------------------------------------------------
Which type of computer do you use?
[1] Desktop
[2] Integrated Desktop
[3] Notebook

**Comment by fourdollars** [comment]
I have added new option '--report' to generate better report.

**Comment by fourdollars** [comment]
I have added new option '--report' for better output.
