### ISSUE TITLE
switch those two questions about graphic and ignore one if possible

### ISSUE THREAD

**Issue by ycheng** [fourdollars/energy-tools#3]
As run the tools:
-----------------
[A]
Does it have switchable graphics and automated switching enabled by default?
Switchable Graphics: Functionality that allows Discrete Graphics to be disabled
when not required in favor of Integrated Graphics. [y/n]
-----------------
[B]
How many discrete graphics cards?
-----------------
Can we ask the user [B] about the number of discrete graphics cards? If it's 0, then we don't need to ask [A] anymore.

**Comment by fourdollars** [comment]
I have the same idea before.
I remember the spec doesn't follow this way.

**Comment by ycheng** [comment]
: ~ not user-friendly....
